### ISSUE TITLE
[Bug] Autocomplete results hidden behind Filters box when searching visual novels

### ISSUE THREAD

**Issue by keacastroga** [marcussacana/VNDB-Extender-2020#1]
When attempting to add filters to a search from the Browse visual novels page the first few autocomplete results get hidden behind the Filters box:
![image](https://user-images.githubusercontent.com/9562862/72690294-00986600-3ae9-11ea-9e3b-3ee8c86ca2b2.png)

**Comment by marcussacana** [comment]
Fixed, thx for the report.
![image](https://user-images.githubusercontent.com/10576957/72858934-13ee3180-3ca1-11ea-8713-3d88a9c88832.png)

Sorry for the wait, my internet don't worked for some days
