### ISSUE TITLE
Removed titles prevent loading of additional images

### ISSUE THREAD

**Issue by RecursiveFault** [marcussacana/VNDB-Extender-2020#11]
This is a huge edge case but I have Juusei Kihei Boueiken in my vndb list, and it as well as every other entry after it do not populate their image likely just due to an edge case HTTP error. 
![image](https://user-images.githubusercontent.com/9141744/109673666-3f9a4700-7b44-11eb-8895-b8c530b19e29.png)

**Comment by marcussacana** [comment]
Thanks for the feedback, I will need samples to analyze like the html of the page and the server responses also the  console logs, but it's hard to ask anyone to share it because those info are enough to gain access to an account. First I will try do something alone, then I will need time to fix it

**Comment by marcussacana** [comment]
What browser are you using?

**Comment by marcussacana** [comment]
Can you test to me this version of the extension? Load as unpacked extension and disable the original extension for a while, then test if the problem is solved.
[VNDB-Extender-2020.zip](https://github.com/marcussacana/VNDB-Extender-2020/files/6072960/VNDB-Extender-2020.zip)

**Comment by RecursiveFault** [comment]
Using chrome, same issue when loading that version as unpacked. I actually checked and found this as an error though: 
![image](https://user-images.githubusercontent.com/9141744/109854650-49e04200-7c25-11eb-94aa-911a249136f4.png)

**Comment by RecursiveFault** [comment]
To be clear, this vn has been removed from the database and I just kinda wanted to keep it. Not a big deal at all, and couldnt be recreated bc it cant be added anymore.

**Comment by marcussacana** [comment]
Try this now:
[VNDB-Extender-2020.zip](https://github.com/marcussacana/VNDB-Extender-2020/files/6079946/VNDB-Extender-2020.zip)
if not works show the error like you did before plz

**Comment by marcussacana** [comment]
....?

**Comment by RecursiveFault** [comment]
Apologies, my day job has been exceedingly busy. Interestingly this seems to have wiped out the display of any entry: 
![image](https://user-images.githubusercontent.com/9141744/110169731-1b9a6800-7dc7-11eb-9956-56ec2c956c6a.png)

**Comment by RecursiveFault** [comment]
Errors: 
![image](https://user-images.githubusercontent.com/9141744/110169851-4b497000-7dc7-11eb-9d00-5179ddf08bc6.png)

**Comment by marcussacana** [comment]
This one now...
[VNDB-Extender-2020.zip](https://github.com/marcussacana/VNDB-Extender-2020/files/6094157/VNDB-Extender-2020.zip)

**Comment by RecursiveFault** [comment]
![image](https://user-images.githubusercontent.com/9141744/110228856-8edcd080-7ed2-11eb-8b18-9bee32a962b0.png)

![image](https://user-images.githubusercontent.com/9141744/110228860-956b4800-7ed2-11eb-8e20-9daac73c5132.png)

**Comment by marcussacana** [comment]
Now this
[VNDB-Extender-2020.zip](https://github.com/marcussacana/VNDB-Extender-2020/files/6097138/VNDB-Extender-2020.zip)

**Comment by RecursiveFault** [comment]
![image](https://user-images.githubusercontent.com/9141744/110521741-2104f480-80de-11eb-81e0-b2000cac2763.png)
No errors in the console this time

**Comment by marcussacana** [comment]
My god

**Comment by marcussacana** [comment]
Can you send link to your VN list in the page of this problem?
