### ISSUE TITLE
can't manage labels while the extension on

### ISSUE THREAD

**Issue by ghost** [marcussacana/VNDB-Extender-2020#3]
the setting doesn't appear at all and just showing "VN labels private" when managing labels. I turned off the extension and it's working again. it happened in Firefox and not sure if it is the same on other browser.
![Screenshot_2020-05-08 My list vndb](https://user-images.githubusercontent.com/65012761/81388101-fce52980-9141-11ea-9350-cc730d5898ae.png)

**Comment by marcussacana** [comment]
I will take a look
