### ISSUE TITLE
it loads the covers way to slow

### ISSUE THREAD

**Issue by markdole3** [marcussacana/VNDB-Extender-2020#4]
big issue

**Comment by marcussacana** [comment]
You tried enable the Async Covers?
![image](https://user-images.githubusercontent.com/10576957/86230322-50368f80-bb67-11ea-80e7-bd97c916ccc2.png)

And how slow is to you?
This 'slowdown' in the title loading is something made intentionally.
Usually the VNDB give a ban ip to you if you made very fast requests to the site,
and without the slowdown, you do around 100 requests per page to the VNDB server.
It's very probabby to get a ban ip for that.
