### ISSUE TITLE
some of the NSFW covers don't get blurred

### ISSUE THREAD

**Issue by ghost** [marcussacana/VNDB-Extender-2020#6]
actually, most of them don't. this doesn't only happen on my VN list, but on the other places too e.g. the browse visual novels section.
my browser is firefox. I have tried clearing the cache but it doesn't seem to work.

![sdas](https://user-images.githubusercontent.com/65012761/88400272-4e708c80-cdf2-11ea-9d70-77fa80cfed1b.jpg)

**Comment by marcussacana** [comment]
Send me the vndb link of any VN that the cover nsfw shows
I probabbly know what happen but Just to confirm.

**Comment by ghost** [comment]
not blurred:
https://vndb.org/v21087
https://vndb.org/v14779
https://vndb.org/v13763
https://vndb.org/v26757

blurred:
https://vndb.org/v28539
https://vndb.org/v2984
https://vndb.org/v15761

I included both of them just in case

**Comment by marcussacana** [comment]
You probabbly disabled the VNDB nsfw check, rigth?
Well, I will take a look into this.

**Comment by marcussacana** [comment]
Nop... Isn't what I think before... hmm strange, what browser you used?

**Comment by marcussacana** [comment]
Can you send a link of this page that those VNs appear in the list?

**Comment by marcussacana** [comment]
Ohh, check if you aren't running the version 2.8.4? If yes, then this bug is only because still outdated, the microsoft take a time to verify the extension and allow everyone update, you can just wait or use the extension from the source in this repo.

**Comment by ghost** [comment]
I'm on Firefox developer edition and the extension version is 2.8.5.
I tried everything that I can think of, like turning off all extensions aside from the extender, clearing my browser data, updating my browser, reinstalling the extender but nothing really works.
the thing is, it works just fine in Chrome so I assume the problem has something to do with the browser.
I'm thinking of reinstalling Firefox but I don't think it will bring any change since I just recently reinstalled it anyway.

**Comment by ghost** [comment]
so in the end, I reinstalled Firefox and the extender again and... it worked. 
alright, I suppose there's something wrong with my browser setting but I don't really know what it is, never really changed anything notable, only minor stuff such as smooth scrolling etc.
it reminds me, sometimes the preview cover doesn't change according to real cover, when in reality it has changed. so that got me thinking, is the extender cache is actually separated from browser cache? if so, then tell me how to empty the cache since it might be the reason why those bugs happened to me.

**Comment by marcussacana** [comment]
yes, he have a very persistent cache, to clean usually you can reinstall the extension or clear the entire browser cache data.
Well, if is a problem only with the firefox this can be the reason that I don't found the bug, because my one is a chromium based browser.
I will take a look soon into this.

**Comment by marcussacana** [comment]
Okay, I downloaded the firefox but I don't found the bug.
If possible send the exact link of the page that you saw the problem.

**Comment by ghost** [comment]
yeah it seems even myself can't reproduce the bug. the cause is most likely how Firefox handle cache, since even when I cleared it to make VN covers updated, they didn't change at all.
Oh, and I remember that the blur bug happened while I updated the extension without uninstalling / emptying the cache.

**Comment by marcussacana** [comment]
Okay, if you found why happen just re-open the issue at anytime.
