### ISSUE TITLE
How do you use this extension. 

### ISSUE THREAD

**Issue by moneybags-cloud** [marcussacana/VNDB-Extender-2020#8]
Nevermind I'm a moron. I found out what I was doing wrong. This may be a bug. I have to click on the visual novel tag then the extensions loads. If I go straight to the character trait tab from sidebar and mess around with character filters it will not load the extension.

**Comment by marcussacana** [comment]
I really don't get, but i'm glad that your problem is solved.
If you think anything is wrong because of a bug just report.
